metadata:
  name: "nginxkar"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - name: "nginx"
        image: "nginx:stable"
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: "nginx"
  replicas: 1
